title: Receptenboek
description: Een collectie van heerlijke recepten
url: "https://jverbruggen.github.io"
baseurl: "/receptenboek"

markdown: kramdown
highlighter: rouge
theme: minima

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids: true
  parse_block_html: true
  parse_span_html: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Build settings
include:
  - Recepten2025.md

exclude:
  - .git/
  - .github/
  - README.md
  - Gemfile
  - Gemfile.lock
  - raw/

# Enable HTML in markdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Site settings
show_excerpts: false
safe: false